version: '3.9'
services:
  logging:
    image: datalust/seq:latest
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_ADMINPASSWORDHASH: FFGLEHxmbIEuIow7uGakQVxm9aGu1JijrnG2LzdyDTDanSoCtg==
    ports:
      - "5341:5341"
      - "8085:80"
    volumes:
      - "logging_data:/data"
volumes:
  logging_data: