name: Brooks Builds Main Workflow
on:
  - push
  - pull_request
jobs:
  lint_platform:
    name: Check the Platform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Clippy
        run: cargo clippy
        working-directory: platform/webapp
      - name: Run Formatter
        run: cargo fmt
        working-directory: platform/webapp
